### ISSUE TITLE
Add dependency injection 

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/universal-wallet-interop-spec#2]
See https://github.com/transmute-industries/universal-wallet/issues/29

**Comment by OR13** [comment]
We might consider refactoring to a builder pattern, where support for interfaces was added incrementally, with dependency injection:


```
const wallet = await UniversalWallet.default()
.add(didKeyPlugin)
.add(vcPlugin)
.add(zcapPlugin)
.add(edvPlugin)
.build()
```

**Comment by kimdhamilton** [comment]
I believe this addresses my comment here: https://github.com/w3c-ccg/universal-wallet-interop-spec/issues/46#issuecomment-742900384
> We might consider refactoring to a builder pattern, where support for interfaces was added incrementally, with dependency injection

I think with your PR, this issue can be closed. Looks like you have the machinery in place and we can keep building on it.

**Comment by OR13** [comment]
yes, I am closing
