### ISSUE TITLE
Universal Wallet and interoperability 

### ISSUE THREAD

**Issue by NTonani** [w3c-ccg/universal-wallet-interop-spec#30]
Interoperability _may_ not just suggest protocol interop (I.e. exchange credentials with a user using a different wallet), it may also suggest interoperability of data, creating a 1-n wallet-application relationship. 

We should be concrete in this definition.

**Comment by kimdhamilton** [comment]
Hey @NTonani, can you provide more details on this? Is this referring to something already in the spec, or a suggestion for new content? We can start iterating in this issue.

**Comment by NTonani** [comment]
@kimdhamilton Interoperability of data suggests both application A and B can access the same credential through the wallet. Some of the challenges this presents (application auth, shared storage) aren't in spec at the moment. 

We should either look to support such interoperability or be explicit about not!

**Comment by OR13** [comment]
This sounds to me like more of a wallet instance specific concern, for example when I add the same mnemonic to 2 wallets, both can transfer associated crypto currencies.

This is powered by a shared data model, which is covered by the data model side of the spec>>>

Are you thinking about this a different way?

**Comment by NTonani** [comment]
> This is powered by a shared data model, which is covered by the data model side of the spec>>>

This is covered by the spec, yes! 💪

> Are you thinking about this a different way?

Thinking through the lens of shared wallets; data access and storage patterns. The spec terminology has become more clear in defining its boundaries and don't see this as a concern anymore. 

Closing!
