### ISSUE TITLE
It's not possible to type the letter "a" in the Generate wallet dialog

### ISSUE THREAD

**Issue by gjgd** [w3c-ccg/universal-wallet-interop-spec#32]
- Go to https://w3c-ccg.github.io/universal-wallet-interop-spec/storybook/?path=/story/cards-wallet--unlocked
- Click the three dots on the top right of the wallet
- Click Generate
- Try to enter the letter "a" -> not possible

One possible cause for this bug is that a parent component is catching the keyboard event associated with typing "a" and doesnt forward it to the text input.

Maybe the Fullscreen component ?

**Comment by OR13** [comment]
I believe I fixed this in one of the massive refactors
