### ISSUE TITLE
need for a did:web plugin 

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/universal-wallet-interop-spec#37]
We are seeing increasing need for a did:web plugin similar to the did:key plugin already provided.  This will enable us to integrate the wallet more easily with external systems looking to support DIDs in a manner that leverages an external domain to bootstrap trust based on knowledge of that external's domains reputation.

**Comment by OR13** [comment]
This should be pretty straight forward:

this is the plugin code for did:key https://github.com/w3c-ccg/universal-wallet-interop-spec/tree/master/packages/did-key-plugin

here is the plugin code for sidetree.js: https://github.com/transmute-industries/sidetree.js/tree/master/packages/wallet

in particular, here is the code for an interop profile we are developing for SVIP:

https://github.com/transmute-industries/sidetree.js/blob/master/packages/wallet/src/functions/toDidDocForProfile.test.ts

it only uses Ed25519 and X25519 keys.

If you feel like contributing to material ui / react... here is an example of UI that is powered by the wallet plugins:

https://w3c-ccg.github.io/universal-wallet-interop-spec/storybook/?path=/story/dialogs-interface--generate

**Comment by OR13** [comment]
https://github.com/w3c-ccg/universal-wallet-interop-spec/pull/55
