### ISSUE TITLE
correct npm scoping

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/universal-wallet-interop-spec#41]
current scoping is primarily `@transmute/... `instead of `@w3c-ccg/...`, for example:
`import * as fixtures from '@transmute/universal-wallet-test-vectors';`
instead of
`import * as fixtures from '@w3c-ccg/universal-wallet-test-vectors';`

@OR13 any objections?

**Comment by mprorock** [comment]
nb: this will require a w3c-ccg namespace on npmjs to fully do - alternative would include removing the namespace scope, but this could make it harder for others to engage with or leverage the project

**Comment by OR13** [comment]
yep, I am not opposed to publishing to a shared namespace, I have setup similar  for 

https://www.npmjs.com/package/@material-did/universal-wallet

https://www.npmjs.com/package/@sidetree/wallet

its just extra work.

**Comment by mprorock** [comment]
re-opening until this gets resolved by @w3c-ccg/chairs

**Comment by OR13** [comment]
This is never going to get fixed.... I suggest we close this and rely on contributors to host software.

**Comment by OR13** [comment]
Closing this, there is a new npm owner for this libraries in this repo.
