### ISSUE TITLE
Add Add and Remove interfaces to spec

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/universal-wallet-interop-spec#69]
There will be a separate issue discussing interface/plugin grouping. Per discussion in #46, Add / Remove accepted types are expected to correspond to specific "flavors" (e.g., Currency wallet vs VC wallet).

Nonetheless, Query is defined in the spec interfaces, so I'm assuming Add and Remove belong there as well, even if that's realized by grouping into a Storage interface.

Some examples I expect we'll want to handle follow:

- Add(VC | VP): VC related
- Add(Currency): Currency related
- Add(MetaData):  Add some non-standard application data that's linked via metadata

Remove is similar

**Comment by sudeshrshetty** [comment]
We can introduce `add/remove` interfaces to spec. And also, `get` (to get a wallet content directly by id).

We can standardize these interfaces to support any data models, for example to add credential 

```
let type = 'credential' // data model type
let vc = ..... // credential data model
wallet.add(type, vc)
// note: we also need to pass collection id somehow in above function call for grouping VCs
```

The only drawback I can think of now is that, few data models may have correlation with other data models.
For example: A [credential](https://w3c-ccg.github.io/universal-wallet-interop-spec/#Credential) can belong to a specific [collection](https://w3c-ccg.github.io/universal-wallet-interop-spec/#Collection). We may have to consider such scenarios while adding/removing the data models.

**Comment by sudeshrshetty** [comment]
@kimdhamilton we may also have to consider [this](https://github.com/w3c-ccg/universal-wallet-interop-spec/issues/73)

**Comment by OR13** [comment]
I did this work, https://w3c-ccg.github.io/universal-wallet-interop-spec/#add I am going to close this for now.
