### ISSUE TITLE
wallet interfaces for WACI - share flow

### ISSUE THREAD

**Issue by sudeshrshetty** [w3c-ccg/universal-wallet-interop-spec#99]
Based on recent progress in [Wallet And Credential Interactions](https://identity.foundation/waci-presentation-exchange/) spec, I would like to propose few interfaces in universal wallet to support WACI.

Flow between prover(wallet) & verifier for [share flow](https://identity.foundation/waci-presentation-exchange/#interoperability-profile),
1. verifier sends out-of-band invitation to wallet.
2. wallet sends message proposing presentation to verifier.
3. verifier replied with message requesting presentation from wallet. 
4. wallet performs query, prepares presentation and displays results in UI for user.
5. wallet presents proof to verifier after taking user's consent in UI.
6. verifier sends optional acknowledge message back to wallet for redirecting.

Interface Suggestion:
- a wallet implementation may or may not support DIDComm V2 yet. In case of DIDComm V2 a wallet may not need to implement `connect(invitation)` interface. So we can define a generic interface like this to accept invitation & send propose presentation message.

```
 // accept the invitation, send message proposing presentation, wait and return presentation request.
 let request = await wallet.proposePresentation(invitation, from, timeout)
 
 //  Args 
 //  invitation: out-of-band invitation 
//   from: optional in case of DIDComm V1 and a wallet can choose a specific DID to send the message in case of DIDComm V2 
// timeout: optional timeout duration to wait for presentation request from verifier.
```

- to accept presentation request and present proof
```
 // send result presentation (query result) to verifier as part of present proof message and get acknowledgement back.
 let ack = wallet.presentProof(thID, presentation, timeout)
 
 //  Args 
 //  thID: thread ID of the intercation 
//   presentation: presentation to be submitted from wallet to verifier
// timeout: optional timeout duration to wait for presentation request from verifier.
```

Example of share flow:

```
// accept invitation, send propose presentation message and presentation request 
let request = await wallet.proposePresentation(invitation, "did:example:wallet:123", someTimeout)

// extract presentation definition(s) from request
let presentationDef = extractPresentationDef(request)

// perform query in wallet  (existing interface)
let presentation = await wallet.query([
           {
            type: "PresentationExchange",
            credentialQuery: presentationDef
            }
])

/* 
 show result to wallet user and get consent
*/

// add proof to presentation (existing interface)
let vp = await wallet.prove(presentation, proofOptions)

// send present proof message to verifier and get acknowledgement for next step
let ack = await wallet.presentProof(request.thid, presentation, someTimeout)
```

**Comment by sudeshrshetty** [comment]
@OR13 please have a look and let me know about your views.

**Comment by OR13** [comment]
@sudeshrshetty yes, this looks good.

for the VC HTTP API side of this, we have this flow implemented, for example:

https://github.com/OR13/GNARLY/blob/main/src/__tests__/Exchange/Exchange.test.ts

and an older implementation of it that predates WACI:

https://github.com/transmute-industries/verifiable-data/blob/main/packages/universal-wallet-vp-exchange-plugin/src/__tests__/vp-exchange.spec.ts

I've very excited to add our first bits of DID Comm when we add support for WACI.
